// Code generated by MockGen. DO NOT EDIT.
// Source: internal/platform/http/quakeLog.go

// Package quakelog is a generated GoMock package.
package quakelog

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQuakeLog is a mock of QuakeLog interface.
type MockQuakeLog struct {
	ctrl     *gomock.Controller
	recorder *MockQuakeLogMockRecorder
}

// MockQuakeLogMockRecorder is the mock recorder for MockQuakeLog.
type MockQuakeLogMockRecorder struct {
	mock *MockQuakeLog
}

// NewMockQuakeLog creates a new mock instance.
func NewMockQuakeLog(ctrl *gomock.Controller) *MockQuakeLog {
	mock := &MockQuakeLog{ctrl: ctrl}
	mock.recorder = &MockQuakeLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuakeLog) EXPECT() *MockQuakeLogMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockQuakeLog) Get() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockQuakeLogMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockQuakeLog)(nil).Get))
}
